### ISSUE TITLE
Profile banner does not stretch to fit space

### ISSUE THREAD

**Issue by nexy7574** [officialdakari/Extera#34]
### Describe the bug

If you upload a banner image that is smaller than the banner's space, it merely stays as the original size in the top-left corner of the box.

### Reproduction

1. Use a small image, such as [the one I used](https://files.i-am.nexus/u/fSX3rM.webp)
2. See as it only uses a small portion of the allocated space:

[![demo](https://files.i-am.nexus/u/slategray-tubby-curassow.jpg)](https://files.i-am.nexus/u/slategray-tubby-curassow.jpg)

### Expected behavior

Images that are too small are stretched to fit the box (it might just be a missing `width:100%` attribute?)

### Platform and versions

```shell
1. OS: Fedora 40
2. Browser: Firefox 128.0.3
3. Extera version: 1.1 (commit 81627b6)
4. Homeserver: nexy7574.co.uk
```

**Comment by officialdakari** [comment]
Fixed.
